// Code generated by mockery. DO NOT EDIT.

package mock_f_c_p_management_service

import (
	f_c_p_management_service "github.com/hashicorp/hcp-sdk-go/clients/cloud-billing/preview/2020-11-05/client/f_c_p_management_service"
	mock "github.com/stretchr/testify/mock"

	runtime "github.com/go-openapi/runtime"
)

// MockClientService is an autogenerated mock type for the ClientService type
type MockClientService struct {
	mock.Mock
}

type MockClientService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientService) EXPECT() *MockClientService_Expecter {
	return &MockClientService_Expecter{mock: &_m.Mock}
}

// FCPManagementServiceGetConsumptionPool provides a mock function with given fields: params, authInfo, opts
func (_m *MockClientService) FCPManagementServiceGetConsumptionPool(params *f_c_p_management_service.FCPManagementServiceGetConsumptionPoolParams, authInfo runtime.ClientAuthInfoWriter, opts ...f_c_p_management_service.ClientOption) (*f_c_p_management_service.FCPManagementServiceGetConsumptionPoolOK, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params, authInfo)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FCPManagementServiceGetConsumptionPool")
	}

	var r0 *f_c_p_management_service.FCPManagementServiceGetConsumptionPoolOK
	var r1 error
	if rf, ok := ret.Get(0).(func(*f_c_p_management_service.FCPManagementServiceGetConsumptionPoolParams, runtime.ClientAuthInfoWriter, ...f_c_p_management_service.ClientOption) (*f_c_p_management_service.FCPManagementServiceGetConsumptionPoolOK, error)); ok {
		return rf(params, authInfo, opts...)
	}
	if rf, ok := ret.Get(0).(func(*f_c_p_management_service.FCPManagementServiceGetConsumptionPoolParams, runtime.ClientAuthInfoWriter, ...f_c_p_management_service.ClientOption) *f_c_p_management_service.FCPManagementServiceGetConsumptionPoolOK); ok {
		r0 = rf(params, authInfo, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*f_c_p_management_service.FCPManagementServiceGetConsumptionPoolOK)
		}
	}

	if rf, ok := ret.Get(1).(func(*f_c_p_management_service.FCPManagementServiceGetConsumptionPoolParams, runtime.ClientAuthInfoWriter, ...f_c_p_management_service.ClientOption) error); ok {
		r1 = rf(params, authInfo, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientService_FCPManagementServiceGetConsumptionPool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FCPManagementServiceGetConsumptionPool'
type MockClientService_FCPManagementServiceGetConsumptionPool_Call struct {
	*mock.Call
}

// FCPManagementServiceGetConsumptionPool is a helper method to define mock.On call
//   - params *f_c_p_management_service.FCPManagementServiceGetConsumptionPoolParams
//   - authInfo runtime.ClientAuthInfoWriter
//   - opts ...f_c_p_management_service.ClientOption
func (_e *MockClientService_Expecter) FCPManagementServiceGetConsumptionPool(params interface{}, authInfo interface{}, opts ...interface{}) *MockClientService_FCPManagementServiceGetConsumptionPool_Call {
	return &MockClientService_FCPManagementServiceGetConsumptionPool_Call{Call: _e.mock.On("FCPManagementServiceGetConsumptionPool",
		append([]interface{}{params, authInfo}, opts...)...)}
}

func (_c *MockClientService_FCPManagementServiceGetConsumptionPool_Call) Run(run func(params *f_c_p_management_service.FCPManagementServiceGetConsumptionPoolParams, authInfo runtime.ClientAuthInfoWriter, opts ...f_c_p_management_service.ClientOption)) *MockClientService_FCPManagementServiceGetConsumptionPool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]f_c_p_management_service.ClientOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(f_c_p_management_service.ClientOption)
			}
		}
		run(args[0].(*f_c_p_management_service.FCPManagementServiceGetConsumptionPoolParams), args[1].(runtime.ClientAuthInfoWriter), variadicArgs...)
	})
	return _c
}

func (_c *MockClientService_FCPManagementServiceGetConsumptionPool_Call) Return(_a0 *f_c_p_management_service.FCPManagementServiceGetConsumptionPoolOK, _a1 error) *MockClientService_FCPManagementServiceGetConsumptionPool_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientService_FCPManagementServiceGetConsumptionPool_Call) RunAndReturn(run func(*f_c_p_management_service.FCPManagementServiceGetConsumptionPoolParams, runtime.ClientAuthInfoWriter, ...f_c_p_management_service.ClientOption) (*f_c_p_management_service.FCPManagementServiceGetConsumptionPoolOK, error)) *MockClientService_FCPManagementServiceGetConsumptionPool_Call {
	_c.Call.Return(run)
	return _c
}

// FCPManagementServiceListConsumptionPools provides a mock function with given fields: params, authInfo, opts
func (_m *MockClientService) FCPManagementServiceListConsumptionPools(params *f_c_p_management_service.FCPManagementServiceListConsumptionPoolsParams, authInfo runtime.ClientAuthInfoWriter, opts ...f_c_p_management_service.ClientOption) (*f_c_p_management_service.FCPManagementServiceListConsumptionPoolsOK, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params, authInfo)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FCPManagementServiceListConsumptionPools")
	}

	var r0 *f_c_p_management_service.FCPManagementServiceListConsumptionPoolsOK
	var r1 error
	if rf, ok := ret.Get(0).(func(*f_c_p_management_service.FCPManagementServiceListConsumptionPoolsParams, runtime.ClientAuthInfoWriter, ...f_c_p_management_service.ClientOption) (*f_c_p_management_service.FCPManagementServiceListConsumptionPoolsOK, error)); ok {
		return rf(params, authInfo, opts...)
	}
	if rf, ok := ret.Get(0).(func(*f_c_p_management_service.FCPManagementServiceListConsumptionPoolsParams, runtime.ClientAuthInfoWriter, ...f_c_p_management_service.ClientOption) *f_c_p_management_service.FCPManagementServiceListConsumptionPoolsOK); ok {
		r0 = rf(params, authInfo, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*f_c_p_management_service.FCPManagementServiceListConsumptionPoolsOK)
		}
	}

	if rf, ok := ret.Get(1).(func(*f_c_p_management_service.FCPManagementServiceListConsumptionPoolsParams, runtime.ClientAuthInfoWriter, ...f_c_p_management_service.ClientOption) error); ok {
		r1 = rf(params, authInfo, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientService_FCPManagementServiceListConsumptionPools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FCPManagementServiceListConsumptionPools'
type MockClientService_FCPManagementServiceListConsumptionPools_Call struct {
	*mock.Call
}

// FCPManagementServiceListConsumptionPools is a helper method to define mock.On call
//   - params *f_c_p_management_service.FCPManagementServiceListConsumptionPoolsParams
//   - authInfo runtime.ClientAuthInfoWriter
//   - opts ...f_c_p_management_service.ClientOption
func (_e *MockClientService_Expecter) FCPManagementServiceListConsumptionPools(params interface{}, authInfo interface{}, opts ...interface{}) *MockClientService_FCPManagementServiceListConsumptionPools_Call {
	return &MockClientService_FCPManagementServiceListConsumptionPools_Call{Call: _e.mock.On("FCPManagementServiceListConsumptionPools",
		append([]interface{}{params, authInfo}, opts...)...)}
}

func (_c *MockClientService_FCPManagementServiceListConsumptionPools_Call) Run(run func(params *f_c_p_management_service.FCPManagementServiceListConsumptionPoolsParams, authInfo runtime.ClientAuthInfoWriter, opts ...f_c_p_management_service.ClientOption)) *MockClientService_FCPManagementServiceListConsumptionPools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]f_c_p_management_service.ClientOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(f_c_p_management_service.ClientOption)
			}
		}
		run(args[0].(*f_c_p_management_service.FCPManagementServiceListConsumptionPoolsParams), args[1].(runtime.ClientAuthInfoWriter), variadicArgs...)
	})
	return _c
}

func (_c *MockClientService_FCPManagementServiceListConsumptionPools_Call) Return(_a0 *f_c_p_management_service.FCPManagementServiceListConsumptionPoolsOK, _a1 error) *MockClientService_FCPManagementServiceListConsumptionPools_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientService_FCPManagementServiceListConsumptionPools_Call) RunAndReturn(run func(*f_c_p_management_service.FCPManagementServiceListConsumptionPoolsParams, runtime.ClientAuthInfoWriter, ...f_c_p_management_service.ClientOption) (*f_c_p_management_service.FCPManagementServiceListConsumptionPoolsOK, error)) *MockClientService_FCPManagementServiceListConsumptionPools_Call {
	_c.Call.Return(run)
	return _c
}

// SetTransport provides a mock function with given fields: transport
func (_m *MockClientService) SetTransport(transport runtime.ClientTransport) {
	_m.Called(transport)
}

// MockClientService_SetTransport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTransport'
type MockClientService_SetTransport_Call struct {
	*mock.Call
}

// SetTransport is a helper method to define mock.On call
//   - transport runtime.ClientTransport
func (_e *MockClientService_Expecter) SetTransport(transport interface{}) *MockClientService_SetTransport_Call {
	return &MockClientService_SetTransport_Call{Call: _e.mock.On("SetTransport", transport)}
}

func (_c *MockClientService_SetTransport_Call) Run(run func(transport runtime.ClientTransport)) *MockClientService_SetTransport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(runtime.ClientTransport))
	})
	return _c
}

func (_c *MockClientService_SetTransport_Call) Return() *MockClientService_SetTransport_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClientService_SetTransport_Call) RunAndReturn(run func(runtime.ClientTransport)) *MockClientService_SetTransport_Call {
	_c.Run(run)
	return _c
}

// NewMockClientService creates a new instance of MockClientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientService {
	mock := &MockClientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
