# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# Options for analysis running.
run:
  timeout: 10m
  tests: true

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  formats: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

linters:
  fast: false
  enable-all: false
  enable:
    - unused
    - errcheck
    - errorlint
    - goimports
    - gocritic
    - misspell
    - govet
    - ineffassign
    - gofmt
    - gosimple
    - staticcheck
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - dogsled
    - durationcheck
    - usestdlibvars
    - stylecheck
    - paralleltest

linters-settings:
  misspell:
    locale: US
    ignore-words:
      - cancelled

issues:
  exclude:
  - ifElseChain
