# Copyright IBM Corp. 2024, 2025
# SPDX-License-Identifier: MPL-2.0

version: "2"

# Options for analysis running.
run:
  timeout: 10m
  tests: true

# output configuration options
output:
  formats:
    text:
      # print lines of code with issue, default is true
      print-issued-lines: true
      # print linter name in the end of issue text, default is true
      print-linter-name: true
      colors: true

linters:
  enable:
    - unused
    - errcheck
    - errorlint
    - gocritic
    - misspell
    - govet
    - ineffassign
    - staticcheck
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - dogsled
    - durationcheck
    - usestdlibvars
    - paralleltest

  settings:
    misspell:
      locale: US
      ignore-rules:
        - cancelled

  exclusions:
    rules:
      - text: ifElseChain
        linters:
          - gocritic

formatters:
  enable:
    - goimports
    - gofmt
