# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

with-expecter: true
disable-version-string: true
packages:
  github.com/hashicorp/hcp-sdk-go/clients/cloud-iam/stable/2019-12-10/client:
    config:
      dir: "internal/pkg/api/mocks/{{.PackagePath}}"
      outpkg: "mock_{{.PackageName}}"
      all: true
      recursive: true
  github.com/hashicorp/hcp-sdk-go/clients/cloud-resource-manager/stable/2019-12-10/client:
    config:
      dir: "internal/pkg/api/mocks/{{.PackagePath}}"
      outpkg: "mock_{{.PackageName}}"
      all: true
      recursive: true
  github.com/hashicorp/hcp-sdk-go/clients/cloud-billing/preview/2020-11-05/client:
    config:
      dir: "internal/pkg/api/mocks/{{.PackagePath}}"
      outpkg: "mock_{{.PackageName}}"
      all: true
      recursive: true
  github.com/hashicorp/hcp/internal/pkg/api/releasesapi/client:
    config:
      dir: "internal/pkg/api/releasesapi/mocks"
  github.com/hashicorp/hcp-sdk-go/clients/cloud-vault-secrets/preview/2023-11-28/client:
    config:
      dir: "internal/pkg/api/mocks/{{.PackagePath}}"
      outpkg: "mock_{{.PackageName}}"
      all: true
      recursive: true
  github.com/hashicorp/hcp-sdk-go/clients/cloud-vault-secrets/stable/2023-06-13/client:
    config:
      dir: "internal/pkg/api/mocks/{{.PackagePath}}"
      outpkg: "mock_{{.PackageName}}"
      all: true
      recursive: true
