// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ProductListResponse product list response
// Example: ["boundary","consul","nomad","packer","vagrant","vault","waypoint"]
//
// swagger:model product_list_response
type ProductListResponse []string

// Validate validates this product list response
func (m ProductListResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this product list response based on context it is used
func (m ProductListResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
