// Code generated by mockery. DO NOT EDIT.

package mock_product_service

import (
	runtime "github.com/go-openapi/runtime"
	product_service "github.com/hashicorp/hcp-sdk-go/clients/cloud-billing/preview/2020-11-05/client/product_service"
	mock "github.com/stretchr/testify/mock"
)

// MockClientService is an autogenerated mock type for the ClientService type
type MockClientService struct {
	mock.Mock
}

type MockClientService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientService) EXPECT() *MockClientService_Expecter {
	return &MockClientService_Expecter{mock: &_m.Mock}
}

// ProductServiceEstimateCost provides a mock function with given fields: params, authInfo, opts
func (_m *MockClientService) ProductServiceEstimateCost(params *product_service.ProductServiceEstimateCostParams, authInfo runtime.ClientAuthInfoWriter, opts ...product_service.ClientOption) (*product_service.ProductServiceEstimateCostOK, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params, authInfo)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ProductServiceEstimateCost")
	}

	var r0 *product_service.ProductServiceEstimateCostOK
	var r1 error
	if rf, ok := ret.Get(0).(func(*product_service.ProductServiceEstimateCostParams, runtime.ClientAuthInfoWriter, ...product_service.ClientOption) (*product_service.ProductServiceEstimateCostOK, error)); ok {
		return rf(params, authInfo, opts...)
	}
	if rf, ok := ret.Get(0).(func(*product_service.ProductServiceEstimateCostParams, runtime.ClientAuthInfoWriter, ...product_service.ClientOption) *product_service.ProductServiceEstimateCostOK); ok {
		r0 = rf(params, authInfo, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product_service.ProductServiceEstimateCostOK)
		}
	}

	if rf, ok := ret.Get(1).(func(*product_service.ProductServiceEstimateCostParams, runtime.ClientAuthInfoWriter, ...product_service.ClientOption) error); ok {
		r1 = rf(params, authInfo, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientService_ProductServiceEstimateCost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProductServiceEstimateCost'
type MockClientService_ProductServiceEstimateCost_Call struct {
	*mock.Call
}

// ProductServiceEstimateCost is a helper method to define mock.On call
//   - params *product_service.ProductServiceEstimateCostParams
//   - authInfo runtime.ClientAuthInfoWriter
//   - opts ...product_service.ClientOption
func (_e *MockClientService_Expecter) ProductServiceEstimateCost(params interface{}, authInfo interface{}, opts ...interface{}) *MockClientService_ProductServiceEstimateCost_Call {
	return &MockClientService_ProductServiceEstimateCost_Call{Call: _e.mock.On("ProductServiceEstimateCost",
		append([]interface{}{params, authInfo}, opts...)...)}
}

func (_c *MockClientService_ProductServiceEstimateCost_Call) Run(run func(params *product_service.ProductServiceEstimateCostParams, authInfo runtime.ClientAuthInfoWriter, opts ...product_service.ClientOption)) *MockClientService_ProductServiceEstimateCost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]product_service.ClientOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(product_service.ClientOption)
			}
		}
		run(args[0].(*product_service.ProductServiceEstimateCostParams), args[1].(runtime.ClientAuthInfoWriter), variadicArgs...)
	})
	return _c
}

func (_c *MockClientService_ProductServiceEstimateCost_Call) Return(_a0 *product_service.ProductServiceEstimateCostOK, _a1 error) *MockClientService_ProductServiceEstimateCost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientService_ProductServiceEstimateCost_Call) RunAndReturn(run func(*product_service.ProductServiceEstimateCostParams, runtime.ClientAuthInfoWriter, ...product_service.ClientOption) (*product_service.ProductServiceEstimateCostOK, error)) *MockClientService_ProductServiceEstimateCost_Call {
	_c.Call.Return(run)
	return _c
}

// ProductServiceListAvailablePackages provides a mock function with given fields: params, authInfo, opts
func (_m *MockClientService) ProductServiceListAvailablePackages(params *product_service.ProductServiceListAvailablePackagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...product_service.ClientOption) (*product_service.ProductServiceListAvailablePackagesOK, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, params, authInfo)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ProductServiceListAvailablePackages")
	}

	var r0 *product_service.ProductServiceListAvailablePackagesOK
	var r1 error
	if rf, ok := ret.Get(0).(func(*product_service.ProductServiceListAvailablePackagesParams, runtime.ClientAuthInfoWriter, ...product_service.ClientOption) (*product_service.ProductServiceListAvailablePackagesOK, error)); ok {
		return rf(params, authInfo, opts...)
	}
	if rf, ok := ret.Get(0).(func(*product_service.ProductServiceListAvailablePackagesParams, runtime.ClientAuthInfoWriter, ...product_service.ClientOption) *product_service.ProductServiceListAvailablePackagesOK); ok {
		r0 = rf(params, authInfo, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product_service.ProductServiceListAvailablePackagesOK)
		}
	}

	if rf, ok := ret.Get(1).(func(*product_service.ProductServiceListAvailablePackagesParams, runtime.ClientAuthInfoWriter, ...product_service.ClientOption) error); ok {
		r1 = rf(params, authInfo, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientService_ProductServiceListAvailablePackages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProductServiceListAvailablePackages'
type MockClientService_ProductServiceListAvailablePackages_Call struct {
	*mock.Call
}

// ProductServiceListAvailablePackages is a helper method to define mock.On call
//   - params *product_service.ProductServiceListAvailablePackagesParams
//   - authInfo runtime.ClientAuthInfoWriter
//   - opts ...product_service.ClientOption
func (_e *MockClientService_Expecter) ProductServiceListAvailablePackages(params interface{}, authInfo interface{}, opts ...interface{}) *MockClientService_ProductServiceListAvailablePackages_Call {
	return &MockClientService_ProductServiceListAvailablePackages_Call{Call: _e.mock.On("ProductServiceListAvailablePackages",
		append([]interface{}{params, authInfo}, opts...)...)}
}

func (_c *MockClientService_ProductServiceListAvailablePackages_Call) Run(run func(params *product_service.ProductServiceListAvailablePackagesParams, authInfo runtime.ClientAuthInfoWriter, opts ...product_service.ClientOption)) *MockClientService_ProductServiceListAvailablePackages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]product_service.ClientOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(product_service.ClientOption)
			}
		}
		run(args[0].(*product_service.ProductServiceListAvailablePackagesParams), args[1].(runtime.ClientAuthInfoWriter), variadicArgs...)
	})
	return _c
}

func (_c *MockClientService_ProductServiceListAvailablePackages_Call) Return(_a0 *product_service.ProductServiceListAvailablePackagesOK, _a1 error) *MockClientService_ProductServiceListAvailablePackages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientService_ProductServiceListAvailablePackages_Call) RunAndReturn(run func(*product_service.ProductServiceListAvailablePackagesParams, runtime.ClientAuthInfoWriter, ...product_service.ClientOption) (*product_service.ProductServiceListAvailablePackagesOK, error)) *MockClientService_ProductServiceListAvailablePackages_Call {
	_c.Call.Return(run)
	return _c
}

// SetTransport provides a mock function with given fields: transport
func (_m *MockClientService) SetTransport(transport runtime.ClientTransport) {
	_m.Called(transport)
}

// MockClientService_SetTransport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTransport'
type MockClientService_SetTransport_Call struct {
	*mock.Call
}

// SetTransport is a helper method to define mock.On call
//   - transport runtime.ClientTransport
func (_e *MockClientService_Expecter) SetTransport(transport interface{}) *MockClientService_SetTransport_Call {
	return &MockClientService_SetTransport_Call{Call: _e.mock.On("SetTransport", transport)}
}

func (_c *MockClientService_SetTransport_Call) Run(run func(transport runtime.ClientTransport)) *MockClientService_SetTransport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(runtime.ClientTransport))
	})
	return _c
}

func (_c *MockClientService_SetTransport_Call) Return() *MockClientService_SetTransport_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClientService_SetTransport_Call) RunAndReturn(run func(runtime.ClientTransport)) *MockClientService_SetTransport_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientService creates a new instance of MockClientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientService {
	mock := &MockClientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
