// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListProductsV1Params creates a new ListProductsV1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListProductsV1Params() *ListProductsV1Params {
	return &ListProductsV1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewListProductsV1ParamsWithTimeout creates a new ListProductsV1Params object
// with the ability to set a timeout on a request.
func NewListProductsV1ParamsWithTimeout(timeout time.Duration) *ListProductsV1Params {
	return &ListProductsV1Params{
		timeout: timeout,
	}
}

// NewListProductsV1ParamsWithContext creates a new ListProductsV1Params object
// with the ability to set a context for a request.
func NewListProductsV1ParamsWithContext(ctx context.Context) *ListProductsV1Params {
	return &ListProductsV1Params{
		Context: ctx,
	}
}

// NewListProductsV1ParamsWithHTTPClient creates a new ListProductsV1Params object
// with the ability to set a custom HTTPClient for a request.
func NewListProductsV1ParamsWithHTTPClient(client *http.Client) *ListProductsV1Params {
	return &ListProductsV1Params{
		HTTPClient: client,
	}
}

/*
ListProductsV1Params contains all the parameters to send to the API endpoint

	for the list products v1 operation.

	Typically these are written to a http.Request.
*/
type ListProductsV1Params struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list products v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListProductsV1Params) WithDefaults() *ListProductsV1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list products v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListProductsV1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list products v1 params
func (o *ListProductsV1Params) WithTimeout(timeout time.Duration) *ListProductsV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list products v1 params
func (o *ListProductsV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list products v1 params
func (o *ListProductsV1Params) WithContext(ctx context.Context) *ListProductsV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list products v1 params
func (o *ListProductsV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list products v1 params
func (o *ListProductsV1Params) WithHTTPClient(client *http.Client) *ListProductsV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list products v1 params
func (o *ListProductsV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListProductsV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
